language: node_js
sudo: false

node_js:
  - "7"

install:
  - yarn

script:
  - yarn build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: release
  target_branch: master